### ISSUE TITLE
Generate Target File List without Copying

### ISSUE THREAD

**Issue by guiltengine** [EricZimmerman/KapeFiles#164]
Apologies in advance if this is already possible or has been previously requested and I've just missed it.

** KAPE version **
0.8.8.0

**Is your feature request related to a problem? Please describe.**
When running Targets, I would like to be able to search for a certain file or directory and record the path(s) if they were found on a live system without making an actual copy since in some cases it would be unnecessary or undesirable. As a bit of a contrived example, if access to a particular 4GB file was restricted, I would like to know that it was found on an unauthorized user's computer but I wouldn't need a copy saved on my flash drive. 

**Describe the solution you'd like**
A per-target flag specifying whether the file or folder (if found) should be copied to the target destination or just their paths and metadata recorded in separate file list (or maybe in the copy log with a new column noting whether the file was copied or not).

**Describe alternatives you've considered**
Powershell could be used to accomplish this but it would be preferable to keep everything within KAPE without having to maintain and run an additional batch script/wrapper.

**Additional context**
N/A

**Comment by EricZimmerman** [comment]
working on this for 0.9.0.2. I  will add a command line switch, like --simulate that would do everything except copy the file.

the problem with it being target specific is that it complicates things when you have multiple targets on the command line, because which simulate should i do? files are located before copy starts, so copying some targets but not others is not ideal since you may have to touch 20 targets for simulate to work

**Comment by EricZimmerman** [comment]
this is done. works nice, and the Console logging shows (SIMULATED) when --sim is used. The CSVs do not indicate --sim was used
