### ISSUE TITLE
StartupFolders.tkape does not collect startup folder

### ISSUE THREAD

**Issue by 2thewes** [EricZimmerman/KapeFiles#978]
Hi, 
since the latest changes to StartupFolders.tkape the folder `C:\Users\%user%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` is no longer collected. 
Instead the path `C:\Users\%user%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\` is collected which contains links to some installed programms (all that have no subfolder in the start menu) but not the start up folder.

The same applies to the System-wide startup folder (`C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp`)

I dont think that is the exprected behavior for the target.

Maybe @MaxZabuty can give some insight on the changes?

**Comment by MaxZabuty** [comment]
Hi,

Thank you for bringing this to my attention. You’re absolutely correct, my recent changes mistakenly targeted the broader Programs directory rather than focusing specifically on the Startup subdirectory, which is critical for capturing persistence mechanisms.

To clarify, only the contents of the Startup folder (C:\Users\%user%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup) are executed automatically on login and thus gain persistence. The general Programs folder contains shortcuts to installed programs but does not inherently provide persistence. The same applies to the system-wide folder (C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup).

This was an oversight and the target paths should be reverted back to their previous state, ensuring that the collection focuses specifically on the Startup subdirectories as expected.
